### PR TITLE
Update textures

### PR DESCRIPTION
**Pull request by IceflowRE**
Change:
look into the changed files

this png are remade based on the .svg in the Ice data... and unnameds
fu-script (sky, notexture not ;) )

for player symbol i can change the shadow to left (at the moment its
normal like all RE style are)

### CODE REVIEW

**Comment by ZeroKnight** [comment]
Higher res assets are always nice to have, good work. Was just thinking the other day that some were kinda low-res.

**Comment by acerspyro** [comment]
I think we should hunt down all low-res textures in the game and replace them with a similar, or the same, higher res texture.

**Comment by acerspyro** [comment]
info
If you want to include it into the commit, go ahead.

**Comment by IceflowRE** [comment]
What about a blue (like before? :D)
re-logo_blue

The shadow can be smaller or bigger :D (or no shadow)

re-info_blue

**Comment by qreeves** [comment]
Leave it as gray scale, we colour all icons in software for Red Eclipse.

**Pull request merged**
