### PR TITLE
Castle changes/improvements

### PR DESCRIPTION
**Pull request by acerspyro**
Castle gets updated again!
The commit message is pretty much self-explanatory, but I'll still take the time to describe my changes here.

First of all, the ambient lightning, skylight and sunlight have been set to make the environment feel more "candle-lit", the torches are round (They used to be very geometrical), and most important of all, the pillars are round and look awesome.

I added frames to the windows, some ground areas are inset to allow finer details, such as the rounding of the edge up the main ladder, the tower's hat looks less yuck, more straight, curvy and sexy.

I, um, added a jar, um, on top of a teleporter, uh, hum, - insert reason here - , and I've changed the entrances' sides (left and right, you'll notice I used a different texture there).

Now, allow me to dump my classic pile of pictures.

Rounded torches

Rounded pillars

Window frame

Yes, @freezurbern, it's all clipped properly.

Those two walls on each side of entrances/exits I failed to describe properly.

Same thing, but outside.

Forgot rounded ladders.

Nicer tower hat.

The *cough*jar

### CODE REVIEW

**Comment by freezurbern** [comment]
Best version yet. I hope this is merged.

**Comment by shirepirate** [comment]
you have not followed the guidelines for submitting changes (changes must be based off of the most recent map version). this can't be merged, quite simply.

**Comment by acerspyro** [comment]
If I hadn't told you, you wouldn't have noticed. I manually merged the cfgs.

**Comment by shirepirate** [comment]
when you began work on this a couple days ago, why on earth did you not simply base it on the most recent map version? there were several more changes across the board other than the very few changes in the cfg file, you of all people should know how many small things can get changed in a map when you're wandering around in edit. there were material changes, entity changes, geometry changes (and bugs), texture bugs and changes, in both of the commits.

instead you've based this off of a version from 3 commits ago? what were you thinking? and aside from that, you knew better because i told you. even before the 2nd commit i had made, you still weren't basing this off of the most recent version available.

you're suggesting i should go through and try to remember all the changes i made because you couldn't follow the simple content submission guidelines we have? that is why they are even in place, to avoid mistakes like this. please follow them in the future.

*that* is why this can't be merged, it has nothing to do you as a contributor (has there ever been a problem with your contributions in the past?) or some wicked plot against you. you didn't follow the rules, simple as that.

it may require a couple hours of work on your part to copy over the changes, but maybe you won't make the same mistake in the future? and you'll also realize i had already made some of the same changes you've made.

all that aside, the pillars, torches & two walls changes look good, the light entities and world variables have already been replaced, if you change them at all take care it is what the map author originally intended for it at this point. the jar mapmodel is a little odd, is there a reason for it?

**Comment by acerspyro** [comment]
Not really, it's just one of those fun things that you never notice until
you do, and then you go "ah lol". If it annoys you so bad, I can remove it.
Also, I will not clear my changes and base myself on the latest version,
but I will gladly implement the changes done to the map while I was editing
the map if you tell me what changed.

**Pull request closed without merging**
