### PR TITLE
update race map escape

### LINKED ISSUE #20: Escape: Checkpoint angles and sound errors
Just to keep track of these issues on the race map *escape*.
http://redeclipse.net/forum/viewtopic.php?f=5&t=354&start=175#p5605

### PR DESCRIPTION
**Pull request by bonifarz**
* closes #20 
* fix the checkpoint angles
* remove geometry artifacts and unused entities
* recreate most of the lighting and all sound entitites
* remove unused sounds from config

### CODE REVIEW

**Comment by bonifarz** [comment]
I know *escape* still looks a bit strange compared to maps of higher quality, but is there a reason not to merge the fixed problems?

**Comment by shirepirate** [comment]
no, simply didn't notice this PR.
it's worth noting the map author said they are working on a different version of this map, which of course wouldn't be based off of these changes. but we can cross that bridge when we come to it.

**Comment by bonifarz** [comment]
Ah, okay. I tried to contact goku a few times via forum-pm, e-mail and on his ctf-race server. Depending on what he already did maybe he can copy/paste some of the changes I made. E.g. working on the lights was a bit tricky when you still have thousands of them around :stuck_out_tongue_winking_eye:

**Comment by qreeves** [comment]
Holy crap, that's a lot of lights.. :stuck_out_tongue:

**Pull request merged**
