### PR TITLE
texture updates

### PR DESCRIPTION
**Pull request by IceflowRE**
please test maybe the impulse and health bar before (i have no issues)

all based on vector data

I do my best :D

### CODE REVIEW

**Comment by ZeroKnight** [comment]
Look closely at [health.png](https://github.com/red-eclipse/data/blob/master/textures/hud/health.png) and [impulse.png](https://github.com/red-eclipse/data/blob/master/textures/hud/impulse.png); both are just slightly transparent, whereas your revisions are fully opaque. Tweak them to match :) Other than that, they look fine (haven't tested them in game).

Also, just a nitpick but consider using more descriptive pull request titles ;) Something like "Texture updates" instead of the vague "some updates".

**Comment by IceflowRE** [comment]
Oh yeah thanks!
I fixed it

That will not happen again!

**Comment by acerspyro** [comment]
Why is it semi-transparent, actually? Shouldn't it be set to be semi-transparent inside the game itself?

**Comment by IceflowRE** [comment]
just say if it should with transparent or without :D

**Comment by acerspyro** [comment]
Check if non-transparent icons look any better in GUIs than semi-transparent ones.

**Comment by qreeves** [comment]
Generally we handle transparency in the engine (just as we do colour), so solid is better and transparency should only be used in situations where you wanted something to be "more see-through" than the rest of the image.

**Comment by IceflowRE** [comment]
Its able to merge this now :D

**Pull request merged**
