### PR TITLE
update race map tonatiuh

### PR DESCRIPTION
**Pull request by bonifarz**
same as http://redeclipse.net/forum/viewtopic.php?f=5&t=354&start=175#p5874
*     make the wall run on the sphere a bit easier
*    no launch needed in the final part
*    fix two sphere-climb shortcuts (hopefully)
*    update route ents accordingly

### CODE REVIEW

**Comment by bonifarz** [comment]
ton snap1
ton snap2
Not sure if the cfg saved with the map is needed, maybe I should revert those small diffs.

**Comment by shirepirate** [comment]
cfg isn't needed here

**Comment by bonifarz** [comment]
Okay, copied the cfg from https://github.com/red-eclipse/data/blob/master/maps/tonatiuh.cfg in order to revert, but it still shows up as a changed file.

**Comment by bonifarz** [comment]
Thanks quin. I think I figured out how to get my fork updated, so hopefully, the next patch will work better :smile:

**Pull request merged**
