### PR TITLE
Added map model, enhanced map Castle

### PR DESCRIPTION
**Pull request by acerspyro**
I've spent a while of my time this week to enhance Castle. I have made some changes in the pillars, made a bell mapmodel, new teleporters, changed the ladders a little bit, etc.
Just in case it has to be specified, I used LuckyStrike's texture for the bell mapmodel, which I dedicate to the Red Eclipse project.

### CODE REVIEW

**Comment by shirepirate** [comment]
the light effect near the warps is a little strong and creates some strange glitches in the surrounding geometry, see if you can fix it to look more natural without changing precision

the shotgun in the bell tower is a problem, non-explosive weapons must be placed in a location that is easily accessible without parkour moves like wall climb. the weapons placed on the gazebos are a grey area, as there is a playerstart located up there, but they should probably be changed to explosives and the weapons moved elsewhere.

there's this:


all the small windows should probably be clipped off or given the same geometry as the barred windows + clipped off.

while these issues were mostly not the result of your edit, they are fixes that should be made

**Comment by acerspyro** [comment]
About the shotgun in the bell tower, should I put a ladder behind it?

**Comment by shirepirate** [comment]
that should work

**Comment by acerspyro** [comment]
There, thanks shirepirate! I implemented your fixes, and I improved some details here and there.

**Comment by shirepirate** [comment]
did you forget to update the cfg or something? these latest files are bugged, textures are all messed up

**Comment by acerspyro** [comment]
Should be fixed now.

**Comment by bonifarz** [comment]
That's some awesome map enhancements. What are your plans for *center*? Your work in progress looked really nice, so it would be cool to get that merged as well.

**Comment by acerspyro** [comment]
@bonifarz  are progressing, I've added better outside walls and doors. Next, I need to light all the windows, and fix some inconsistencies in the windows' shine (Some reflect light, some don't).

Typing that just gave me an idea, would it be worth it to put an envmap in front of the windows?

**Pull request merged**
