### PR TITLE
Update textures and mapmodel list

### PR DESCRIPTION
**Pull request by IceflowRE**
Update
- jojos grate skins
- Add models to the modellist, which werent active

### CODE REVIEW

**Comment by qreeves** [comment]
You'll have to scale down the 2048 px textures to at least 1024 px unless you have a very good reason to use that much texture memory.

**Comment by IceflowRE** [comment]
I have it tested with 1024px, but for me the many holes were still very pixelated when you're close to it.
I can scale it down to 1024.

**Comment by bonifarz** [comment]
Depends much on the size and location of the mapmodel. If it is somewhere in the background or rather small, the "ugly" texture really does not harm. I wonder, can a smaller unit cell (single hole) of the texture be applied to the mapmodel surface (like a tile)?

**Comment by shirepirate** [comment]
so, rebase with your changed files

**Comment by acerspyro** [comment]
You could always split your mesh in 4 squares and put the texture in all 4 planes, since it's the same texture anyways.

**Pull request merged**
