### PR TITLE
3D version of LuckyStrikeRx's flat fan model.

### PR DESCRIPTION
**Pull request by acerspyro**
I made a 3D variant of LuckyStrikeRX's fan mapmodel, which was a flat spinning image.

The model has 1032 tris and uses LuckyStrike's fan texture.

### CODE REVIEW

**Comment by Evropi** [comment]
Seems a bit high poly for RE, how many verts?

**Comment by qreeves** [comment]
Wouldn't it be better to replace the existing model rather than create a duplicate of it?

**Comment by acerspyro** [comment]
@qreeves Yes, it would, but I was wondering if it could create legal issues or w/e. Now that you propose it, it seems that it doesn't.

**Comment by acerspyro** [comment]
There, I merged the two

**Comment by qreeves** [comment]
The only legal issue when modifying an RE asset is to provide attribution. I make sure everything we have can be upgraded our iterated on by anyone :)

**Comment by acerspyro** [comment]
I'll have to fix the fan's scaling so that we won't have to go thru all the maps changing the scale.
What's the best way to do this? Should I just open an issue and give the updated file, or should I create another pull request?

**Comment by freezurbern** [comment]
Easiest for everyone else is a PR.

**Comment by acerspyro** [comment]
Even tho it's not the same size as the old one (A tiny bit smaller), it still looks ok on the maps I checked (Canals, Ubik, Decay). Unless anyone sees a problem with that, I'm not going to change it.

**Comment by qreeves** [comment]
Just a setting for `mdlscale` should suffice (in the model's config).

**Pull request merged**
