### PR TITLE
Map fixes for erosion, venus, canals and darkness

### PR DESCRIPTION
**Pull request by JeffBobbo**

### CODE REVIEW

**Comment by shirepirate** [comment]
it was still possible to toss the flag to an inaccesible location in Darkness in this version,

sword

i fixed it though.

in erosion (and in several maps with delicate geometry) you need to be very careful when adding materials to use the same cube size, or the engine will mess up the existing geometry.

original:
after

this edit:
before

there are cases (like this one probably) where material simply can't be added without messing something up. just leave these alone unless they cause a large problem. that isn't the case here, so the erosion changes were not added.

**Comment by JeffBobbo** [comment]
For erosion, without the noclip (or clip), you get stuck on the end of the wall run, very annoying.

**Comment by freezurbern** [comment]
@JeffBobbo If you're going to clip or noclip those on erosion, it'd be best to make it not look corrupted/trashed. I'd say looking like this isn't worth the noclip.

**Comment by JeffBobbo** [comment]
That doesn't look really any different from before (at least, not to the extent that it's obviously different without comparing the two). I believe the idea here is that it's meant to look broken.

**Comment by freezurbern** [comment]
This is what the map is supposed to look like.

**Comment by IceflowRE** [comment]
I dont like the map change on darkness because its not possible anymore to "hide" the flag there and particularly grenades and mines explode now without a visible reason.

**Comment by shirepirate** [comment]
@freezurbern 
erosion is not supposed to look like that, the destroyed effect is on purpose and created by greaserpirate.

@IceflowRE 
the death material was added to items & affinities could not get caught up there, whether accidental or on purpose. it is counter-productive to gameplay. the death barrier on top is high enough that explosives will rarely go off, and when they do it shouldn't affect players.

**Pull request closed without merging**
